### ISSUE TITLE
Show Dialog Box for input

### ISSUE THREAD

**Issue by andy4222** [alfredapp/automation-tasks#3]
A great Automation Task would be to pop up a dialog box (maybe macOS dialog box) with multiple input fields to take user input. Instead of using multiple Script Filters to do this which doesn't work well and is too complicated. Like this one

![image](https://user-images.githubusercontent.com/16066246/177022130-9b799167-7620-41d7-bea8-2086eb439210.png)

**Comment by vitorgalvao** [comment]
Multiple Script Filters would indeed be complex for this. What you should use is multiple Keywords connected to Arg and Vars utilities.

AppleScript dialogs don’t have an option for multiple inputs, which means implementing this as an Automation Task would require a more complex low-level solution. Also, making a general configuration which would work in GUI alone like you have in your example would be far from trivial.

There are still many Automation Tasks planned and that would be too complex for the amount of use it would get, especially considering there is a quick workaround. Not saying it won't happen, but right now is soon to commit to it. It needs further thought put into it.

Final note: I read pretty much every forum post, so no need to make a duplicate request on GitHub for something which was asked there.

**Comment by andy4222** [comment]
Could you please elaborate on the multiple Keywords connected to Arg and Vars? 

Thanks for reading the post on the forum. Unfortunately, I have no good way of knowing that unless someone reacts or comments on that stating what shared above :)

**Comment by vitorgalvao** [comment]
> Could you please elaborate on the multiple Keywords connected to Arg and Vars?

Use multiple [Keyword Inputs](https://www.alfredapp.com/help/workflows/inputs/keyword/) connected to [Argument and Variables Utilies](https://www.alfredapp.com/help/workflows/utilities/argument/). In the latter, you set some variable name with the value of `{query}`. This will allow asking for input in succession, saving it for when you need later, where you’ll reference it back from the variable names.

> I have no good way of knowing that someone has read it, unless someone reacts or comments

Naturally! It was no more than a future note.
