### ISSUE TITLE
Convert Image Format fails if output folder does not exist

### ISSUE THREAD

**Issue by luckman212** [alfredapp/automation-tasks#5]
Hi @vitorgalvao 

Today I decided to try out AT to convert some TIFF images (from clipboard history) to PNG format for editing in CleanShot X. (Works great!)

Only problem is, I selected `/tmp/converted_images` as my Output Folder so I can clean up those temp files later. I tested the workflow again after deleting this folder, and it fails. It converts the image but instead of recreating the missing output folder, it simply named the output file as the folder name. I tried to look at [the code](https://github.com/alfredapp/automation-tasks/blob/main/Tasks/com.alfredapp.automation.core/image-manipulation/image.format.convert/alfredtask.json) but with all the backslash escaping I found it a bit hard to grok.

I'm sure it's a simple fix of testing for the output folder's existence and creating it if missing.

Thank you!

<img width="948" alt="image" src="https://user-images.githubusercontent.com/1992842/188503635-c3e5c5c9-747a-4bae-b44f-6dd1ddbee1c1.png">

**Comment by vitorgalvao** [comment]
Thank you for yet another nice catch! This has been fixed in 2022.14.
