### ISSUE TITLE
Search automation tasks

### ISSUE THREAD

**Issue by andy4222** [alfredapp/automation-tasks#7]
Would be nice to have the ability to search through all the tasks.

**Comment by vitorgalvao** [comment]
That is an [Alfred Request](https://www.alfredforum.com/forum/5-alfred-feature-suggestions/), not an Automation Tasks request. And it’s already possible in Alfred 5.1 (currently in pre-release). It can be turned on in [the Automation Tasks preferences](https://www.alfredapp.com/help/workflows/automations/automation-task/#update).
