### ISSUE TITLE
Get list of running process/apps

### ISSUE THREAD

**Issue by andy4222** [alfredapp/automation-tasks#8]
Would be great to have this "Get list of running process/apps"

**Comment by vitorgalvao** [comment]
A raw list of processes isn’t terribly useful on its own. That’s normally only useful with context such as CPU usage. Could you please expand on your use case? The more you expound on a request, the better thought out it can be.

You have a forum account, so please make the request in the [Automation Tasks subforum](https://www.alfredforum.com/forum/49-workflow-automation-tasks/) where we can discuss further.
